class TransactionPool:
    def __init__(self):
        self.transaction_map = {} # key/value collection

    def set_transaction(self, transaction):
        """
        Set a transaction in the transaction pool
        """
        self.transaction_map[transaction.id] = transaction

    def existing_transaction(self, address):
        """
        Will find a transaction generated by the address in the transaction pool
        """
        # will iterate through all the transaction objects
        for transaction in self.transaction_map.values():
            if transaction.input['address'] == address:
                return transaction

    def transaction_data(self):
        """
        Return the transactions of the transaction pool represented in their json serialized form.
        """
        # transaction data
        # the method returns json so we need to map it
        return list(map(
                lambda transaction: transaction.to_json(), 
                self.transaction_map.values()
            ))
