const BASE_URL = 'http://localhost:5000';
const NANOSECONDS_PYTHON = 1;
const MICROSECONDS_PYTHON = 1000 * NANOSECONDS_PYTHON;
const MILLISECONDS_PYTHON = 1000 * MICROSECONDS_PYTHON;

export{BASE_URL, MILLISECONDS_PYTHON};